---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r loading}
activity_df <- read.csv("activity.csv")
```

## What is mean total number of steps taken per day?
```{r mean_total_number_of_steps_taken_per_day}
act_wo_na <- activity_df[!is.na(activity_df[,1]),]
days <- unique(act_wo_na$date)
no_of_days <- length(days)
sum_of_steps <- sum(act_wo_na$steps)
no_of_steps_per_day <- sum_of_steps/no_of_days
## Printing number of steps per day
no_of_steps_per_day

steps_var <- setNames(aggregate(activity_df$steps,list(activity_df$date), FUN = sum, na.rm= TRUE)
                      ,c("Date","Sum"))

hist(steps_var$Sum,breaks=61)

mean_steps <- mean(steps_var$Sum)
mean_steps

median_steps <- median(steps_var$Sum)
median_steps


```


## What is the average daily activity pattern?
```{r}
steps_at_diff_interval <- setNames(aggregate(activity_df$steps,
                                    list(activity_df$interval), FUN = mean, na.rm= TRUE),
                                   c("Interval","mean"))

plot(steps_at_diff_interval$Interval,steps_at_diff_interval$mean,type="l",xlab="Interval",ylab="Number of steps")
max_steps <- max(steps_at_diff_interval$mean)
max_steps
max_steps_interval <- subset(steps_at_diff_interval,mean == max_steps)[1,1]
max_steps_interval
```

## Imputing missing values

```{r}
no_of_nas <- sum(is.na(activity_df))
no_of_nas

activity_df_mod <- activity_df
### Inserting median for that interval to the na values
activity_df_mod$steps[is.na(activity_df_mod$steps)] <- with(activity_df_mod, ave(steps, interval, 
   FUN = function(x) median(x, na.rm = TRUE)))[is.na(activity_df_mod$steps)]



steps_var_mod <- setNames(aggregate(activity_df_mod$steps,list(activity_df_mod$date), 
                                    FUN = sum, na.rm= TRUE),c("Date","Sum"))

hist(steps_var_mod$Sum,breaks=61)

mean_steps_mod <- mean(steps_var_mod$Sum)
mean_steps_mod

median_steps_mod <- median(steps_var_mod$Sum)
median_steps_mod

if(mean_steps_mod == mean_steps) print("Modified median is same") else print("Not equal")
if(median_steps_mod == median_steps) print("Modified median is same") else print("Not equal")

if(sum(steps_var_mod$Sum) > sum(steps_var$Sum) ) print("Modified sum is greater ") else print("Lesser or equal")
```

## Are there differences in activity patterns between weekdays and weekends?
```{r}
activity_df$weekday <- weekdays(as.Date(activity_df$date))
activity_df$weekday <- replace(activity_df$weekday,activity_df$weekday=="Monday","weekday")
activity_df$weekday <- replace(activity_df$weekday,activity_df$weekday=="Tuesday","weekday")
activity_df$weekday <- replace(activity_df$weekday,activity_df$weekday=="Wednesday","weekday")
activity_df$weekday <- replace(activity_df$weekday,activity_df$weekday=="Thursday","weekday")
activity_df$weekday <- replace(activity_df$weekday,activity_df$weekday=="Friday","weekday")
activity_df$weekday <- replace(activity_df$weekday,activity_df$weekday=="Saturday","weekend")
activity_df$weekday <- replace(activity_df$weekday,activity_df$weekday=="Sunday","weekend")
activity_df$weekday <- factor(activity_df$weekday)

steps_at_diff_interval_mod <- setNames(aggregate(activity_df$steps,
                                    list(activity_df$interval,activity_df$weekday), 
                                    FUN = mean, na.rm= TRUE),
                                   c("Interval","type","mean"))
library(lattice)
xyplot(mean ~ Interval  | factor(type),data = steps_at_diff_interval_mod, 
       xlab="Interval",  ylab="Number of steps",layout=c(1,2),type=c("l"))
```
